# Site settings
title: n.b.
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/notebook-jekyll"
url: "http://yourdomain.com"
twitter_username: freiwasser
github_username:  Kevin-M-Smith
linkedin_username:  ethosengineering

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
