# Site settings
title: n.b.
email: kevin.smith@tufts.edu
description: "Online Lab Notebook"
baseurl: "/notebook-jekyll"
twitter_username: freiwasser
github_username:  Kevin-M-Smith
linkedin_username:  ethosengineering

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
